version: '3.4'

services:
  playlistApi:
    image: ${DOCKER_REGISTRY}playlist
    container_name: playlistApi
    ports:
        - "5555:80"
    build:
      context: .
      dockerfile: PlaylistAPI/Dockerfile
    environment:         - ConnectionString=Server=playlistData;Database=Playlist;User Id=sa;Password=SuperSecret1!     depends_on:        - playlistData    playlistData:     image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: playlistData     environment:         - SA_PASSWORD=SuperSecret1!         - ACCEPT_EULA=Y     ports:         - "1433:1433"
